version: "3.7"

services:
  django:
    build:
      args:
        MODE: development
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      MODE: development
    ports:
      - 80:8000
